// nuxt-example/pages/another.vue
<template>
  <article>
    <h1>Ab debitis deserunt ea velit nostrum vel adipisci nostrum.</h1>
    <p>
      Lorem ipsum dolor sit amet. Ab consequuntur architecto qui sint laudantium
      nam obcaecati dolore et nemo quisquam et quia sint ut obcaecati atque. Qui
      molestias rerum
      <a href="https://www.loremipzum.com" target="_blank"
        >Est sequi et galisum eveniet sit dolorem iste</a
      >. Hic voluptatem velit eos officia evenietut ipsum aut ducimus atque. 33
      molestias accusamus et inventore reprehenderit eos mollitia provident non
      nesciunt nihil rem inventore culpa sit expedita quia.
    </p>
    <h2>Qui itaque dolor id perspiciatis vero sit error doloremque.</h2>
    <p>
      Est asperiores culpa vel dicta quia
      <em>Aut velit aut iure sint in totam dicta</em>. Ut sint enim et officiis
      autem est aliquam velit nam quisquam deserunt non blanditiis consequatur
      sit molestiae odit eos illo illum. At dolor voluptatem
      <a href="https://www.loremipzum.com" target="_blank"
        >Id repellendus est unde deserunt aut eaque rerum</a
      >
      in earum porro ut harum quas.
    </p>
    <h3>Aut reiciendis iste ut quia molestias est nemo pariatur.</h3>
    <p>
      Est quae voluptas ea saepe saepe aut omnis dignissimos qui similique
      doloribus aut omnis a atque laudantium sed dolorem blanditiis. Ut facilis
      dolor et quibusdam eius
      <a href="https://www.loremipzum.com" target="_blank">Est debitis</a>?
    </p>
    <ul>
      <li>Vel eaque vitae qui ducimus molestiae qui sapiente debitis.</li>
      <li>33 rerum nobis qui numquam aspernatur.</li>
      <li>33 eius molestias et optio inventore.</li>
      <li>Nam aperiam ullam est veniam autem et dolorum rerum.</li>
    </ul>
  </article>
</template>

// next-example/pages/another.tsx
import CommentLayout from '@/components/layouts/CommentLayout'

const Another = () => {
  return (
    <CommentLayout>
      <h1>Ab debitis deserunt ea velit nostrum vel adipisci nostrum.</h1>
      <p>
      Lorem ipsum dolor sit amet. Ab consequuntur architecto qui sint laudantium
      nam obcaecati dolore et nemo quisquam et quia sint ut obcaecati atque. Qui
      molestias rerum
        <a href="https://www.loremipzum.com" target="_blank" rel="noreferrer">Est sequi et galisum eveniet sit dolorem iste</a>. Hic voluptatem velit eos officia evenietut ipsum aut ducimus atque. 33
      molestias accusamus et inventore reprehenderit eos mollitia provident non
      nesciunt nihil rem inventore culpa sit expedita quia.
      </p>
      <h2>Qui itaque dolor id perspiciatis vero sit error doloremque.</h2>
      <p>
      Est asperiores culpa vel dicta quia
        <em>Aut velit aut iure sint in totam dicta</em>. Ut sint enim et officiis
      autem est aliquam velit nam quisquam deserunt non blanditiis consequatur
      sit molestiae odit eos illo illum. At dolor voluptatem
        <a href="https://www.loremipzum.com" target="_blank" rel="noreferrer">Id repellendus est unde deserunt aut eaque rerum</a>
      in earum porro ut harum quas.
      </p>
      <h3>Aut reiciendis iste ut quia molestias est nemo pariatur.</h3>
      <p>
      Est quae voluptas ea saepe saepe aut omnis dignissimos qui similique
      doloribus aut omnis a atque laudantium sed dolorem blanditiis. Ut facilis
      dolor et quibusdam eius
        <a href="https://www.loremipzum.com" target="_blank" rel="noreferrer">Est debitis</a>?
      </p>
      <ul>
        <li>Vel eaque vitae qui ducimus molestiae qui sapiente debitis.</li>
        <li>33 rerum nobis qui numquam aspernatur.</li>
        <li>33 eius molestias et optio inventore.</li>
        <li>Nam aperiam ullam est veniam autem et dolorum rerum.</li>
      </ul>
    </CommentLayout>
  )
}

export default Another
