// next-example/pages/index.tsx
import CommentLayout from '@/components/layouts/CommentLayout'

const Home = () => {
  return (
    <CommentLayout>
      <article>
        <h1>Sit earum voluptas est temporibus molestiae vel ducimus fugit.</h1>
        <p>
      Lorem ipsum dolor sit amet. Ut assumenda fugiat est omnis distinctio
          <strong>Et tempora eos voluptates quaerat in illo aliquam</strong>. Ut
      ducimus fugit <em>Ut architecto qui molestias amet</em>.
        </p>
        <h2>Ut iste vitae eum fugiat accusamus.</h2>
        <p>
      Ut omnis harum et eius nostrum
          <em>Et consequuntur est ipsa necessitatibus non ipsam aspernatur eos
        delectus velit</em>. Non corrupti tempora
          <a href="https://www.loremipzum.com" target="_blank" rel="noreferrer">At repellat id minima dicta</a>.
        </p>
        <h3>Qui soluta possimus ut totam voluptatum?</h3>
        <p>
      Ut quae sint ut sunt dolorem
          <a href="https://www.loremipzum.com" target="_blank" rel="noreferrer">Ex aliquid aut dolores nisi ut libero enim ut dolores impedit</a>. Est nulla mollitia cum nobis officia et doloribus eius. Non voluptatem
      velit ut iusto ratione
          <em>In vel voluptas At consequatur incidunt qui neque adipisci</em>.
        </p>
        <ul>
          <li>Et explicabo dolore est voluptatibus recusandae.</li>
          <li>
        Hic tenetur autem ut amet autem At aliquid perferendis eum adipisci
        dolores!
          </li>
          <li>
        Et molestiae consectetur qui odio quibusdam qui accusamus recusandae ut
        temporibus temporibus!
          </li>
        </ul>
      </article>
    </CommentLayout>
  )
}

export default Home

// nuxt-example/pages/index.vue
<template>
  <article>
    <h1>Sit earum voluptas est temporibus molestiae vel ducimus fugit.</h1>
    <p>
      Lorem ipsum dolor sit amet. Ut assumenda fugiat est omnis distinctio
      <strong>Et tempora eos voluptates quaerat in illo aliquam</strong>. Ut
      ducimus fugit <em>Ut architecto qui molestias amet</em>.
    </p>
    <h2>Ut iste vitae eum fugiat accusamus.</h2>
    <p>
      Ut omnis harum et eius nostrum
      <em
        >Et consequuntur est ipsa necessitatibus non ipsam aspernatur eos
        delectus velit</em
      >. Non corrupti tempora
      <a href="https://www.loremipzum.com" target="_blank"
        >At repellat id minima dicta</a
      >.
    </p>
    <h3>Qui soluta possimus ut totam voluptatum?</h3>
    <p>
      Ut quae sint ut sunt dolorem
      <a href="https://www.loremipzum.com" target="_blank"
        >Ex aliquid aut dolores nisi ut libero enim ut dolores impedit</a
      >. Est nulla mollitia cum nobis officia et doloribus eius. Non voluptatem
      velit ut iusto ratione
      <em>In vel voluptas At consequatur incidunt qui neque adipisci</em>.
    </p>
    <ul>
      <li>Et explicabo dolore est voluptatibus recusandae.</li>
      <li>
        Hic tenetur autem ut amet autem At aliquid perferendis eum adipisci
        dolores!
      </li>
      <li>
        Et molestiae consectetur qui odio quibusdam qui accusamus recusandae ut
        temporibus temporibus!
      </li>
    </ul>
  </article>
</template>
